import esbuild from 'esbuild';
import process from 'process';
import fs from 'node:fs';
import { builtinModules } from 'node:module';
import { createRequire } from 'node:module';
import esbuildSvelte from 'esbuild-svelte';
import { sveltePreprocess } from 'svelte-preprocess';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// The ImageMagick engine's JS is bundled into main.js; the 14 MB wasm module
// ships next to it and is read at runtime through the vault adapter. Inlining
// it as base64 would bloat main.js by a third again for no gain.
function copyMagickWasm() {
	const require = createRequire(import.meta.url);
	const src = require.resolve('@imagemagick/magick-wasm/magick.wasm');
	fs.copyFileSync(src, 'magick.wasm');
	console.log('[build] copied magick.wasm');
}

copyMagickWasm();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: 'injected' },
			preprocess: sveltePreprocess(),
		}),
	],
	mainFields: ['svelte', 'browser', 'module', 'main'],
	conditions: ['svelte', 'browser'],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
